### ISSUE TITLE
导入目录错误

### ISSUE THREAD

**Issue by nosoftcn** [Simsv-Software/SimMusic2024-Windows#1]
导入二级目录而并非磁盘根目录（如导入 **E:\music** 目录）会出现 **“您不能导入磁盘根目录”** 错误提示，但按照我的理解二级目录应该并非磁盘根目录。

**Comment by YanJi314** [comment]
感谢反馈，0.0.3 已修复
https://github.com/YanJi314/SimMusic2024/releases/tag/0.0.3
