### ISSUE TITLE
点击歌词跳转偶尔出现问题

### ISSUE THREAD

**Issue by Rs-tr-ric** [Simsv-Software/SimMusic2024-Windows#11]
偶尔情况，点击歌词跳转会跳转到上一句歌词的末尾，然后再切换到点击的那一句（触发概率挺小的）
这样当你在播放这一句歌词的时候点击下一句不会立马切换，而是会切换到这一句的结尾再切换，给人以”延迟“的感觉

下面提供两个有歌词触发这个情况的文件：
花の塔 - さユり
> [00:16.13]くれた知らない名前のお花

ひとりぼっち東京 - 結束バンド
> [01:05.32]わたしの中に青い炎があるから

[examples.zip](https://github.com/user-attachments/files/16638501/examples.zip)

**Comment by YanJi314** [comment]
已复现，正在查找原因，感谢反馈

**Comment by YanJi314** [comment]
![image](https://github.com/user-attachments/assets/61d23e1b-7511-423a-81f8-88ec8d33a544)
浮点数精度损失的锅，下版会为当前进度的毫秒数添加取整，感谢反馈

**Comment by YanJi314** [comment]
0.1.0 已修复  https://www.123pan.com/s/VevLVv-TqWjv
