### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by nosoftcn** [Simsv-Software/SimMusic2024-Windows#2]
1. 播放按钮（主页，非播放页）颜色建议改为主题色蓝色
2. 播放按钮图标视觉不对齐（图标重心偏左），应往右移
3. 进度条与音量条建议取消动画或动画速度加快
4. 主页左侧导航栏建议增加收缩功能
5. 主页左侧导航栏各菜单间距过小，建议增大
6. 主页右上角按钮组建议增加提示
7. 移动到右上角关闭按钮时（包含主页、播放页、弹窗）变红，图标未居中（与Edge浏览器对比更明显，可能由于win11圆角）
8. 窗口大小只能调整到一定程度（不能调整到更小）

**Comment by YanJi314** [comment]
1. 内部讨论中，目前管理组两种说法都有，可能会增加一条设置
2. 下版进行微调，感谢反馈
3. 将针对键盘调整场景进行优化，感谢反馈
4. 0.0.3 已支持导航栏宽度调整
5. 内部讨论中
6. 下版将添加，感谢反馈
7. Win11 未复现，图标均是 `align-items: center; justify-content: center` 标准居中
8. 不计划缩小 minWidth / Height 限制，如有需求请使用 0.0.3 添加的桌面歌词

**Comment by nosoftcn** [comment]
关于第7点的补充：
1. 在非全屏状态出现
2. 可能您的理解错误，指的是下图按钮，可以明显看到图标并未水平居中（0.0.3版本与0.0.2版本均出现）
![屏幕截图 2024-08-14 195039](https://github.com/user-attachments/assets/57022d65-00a5-4265-8887-ee68fc1b1534)

**Comment by YanJi314** [comment]
1. 0.0.4 已增加设置项
2. 0.0.4 已调整
3. 0.0.4 已调整
5. 0.0.4 调整了小标题与上方的间距
6. 已为 除通用的最小化、最大化、关闭按钮 以外的按钮增加提示
