### ISSUE TITLE
无法处理损坏或不可解析的文件

### ISSUE THREAD

**Issue by Rs-tr-ric** [Simsv-Software/SimMusic2024-Windows#3]
尝试导入了更改后缀的空文件与恶意损坏的flac文件，程序在遇到错误的时候直接切换到下一歌曲并发出错误提示音
然而程序并没有“发生错误”的告知，并且在下次播放同一文件的时候，错误依然会发生
希望增加处理这种错误并给出提示的相关功能

**Comment by YanJi314** [comment]
收到，已加入todo，感谢反馈

**Comment by Rs-tr-ric** [comment]
软件在遭遇文件解析的错误的时还会出现一个奇怪行为

举例，列表里有以下文件：

1. 01.wav (broken)
2. 02.wav
3. 03.wav

然后执行以下操作：

1. 双击01.wav，程序尝试播放然后抛出错误，进入等待时间
2. 在等待时间内（此时列表中蓝色高亮显示正在播放的文件依然是01.wav）双击02.wav，使之开始播放

此时会发现过了一段时间（即等待时间结束），程序将自动切换到03.wav开始播放

**Comment by YanJi314** [comment]
0.0.4 已增加错误弹窗  并修复了可能错误切换曲目的bug
