### ISSUE TITLE
桌面歌词动画消失

### ISSUE THREAD

**Issue by nosoftcn** [Simsv-Software/SimMusic2024-Windows#5]
启动后，第一次打开桌面歌词动画存在，关闭又打开动画消失（中途不关闭）

版本	Windows 11 家庭中文版
版本号	23H2
安装日期	‎2024/‎5/‎28
操作系统版本	22635.4005
体验	Windows Feature Experience Pack 1000.22700.1035.0

**Comment by Rs-tr-ric** [comment]
我也遇到了这个问题
根据我的观察，“词”由黑色变为蓝色高亮的逻辑是正常的，然而实际桌面歌词的显示则是每两次“词”由黑色变为蓝色高亮才触发一次（即四次点击有一次触发桌面歌词）
如下
| 点击次数 | “词”的状态 | 桌面歌词是否显示 |
| ---------- | ------------ | -------------------- |
| 0 | 黑色默认 | 不显示 |
| 1 | 蓝色高亮 | 显示 | 
| 2 | 黑色默认 | 不显示 |
| 3 | 蓝色高亮 | 不显示 |
| 4 | 黑色默认 | 不显示 |
| 5 | 蓝色高亮 | 显示 | 
| 6 | 黑色默认 | 不显示 |
| 7 | 蓝色高亮 | 不显示 |
| 8 | 黑色默认 | 不显示 |

**Comment by Rs-tr-ric** [comment]
遇到了相同的问题，奇怪的是，该情况无法稳定复现
大部分时候呈现这样的规律：
| 鼠标点击右上角“词”的次数 | ”词“的显示状态 | 是否显示桌面歌词 |
| - | - | - |
| 0 | 黑色默认 | 否 |
| 1 | 蓝色高亮 | 是 |
| 2 | 黑色默认 | 否 |
| 3 | 蓝色高亮 | 否 |
| 4 | 黑色默认 | 否 |
| 5 | 蓝色高亮 | 是 |
| 6 | 黑色默认 | 否 |
| 7 | 蓝色高亮 | 否 |

但不绝对，偶尔出现例外

**Comment by YanJi314** [comment]
目前「词」按钮快速点击会出现问题
主进程为防止Windows渲染缩放动画，显示歌词浮窗有一定延迟
下版将在主窗口限制快速发送显示 / 隐藏浮窗的指令

补：目前存在歌词浮窗设置「置顶」操作偶现不生效的问题，将在主进程增加处理

补2：上述置顶问题疑似与electron有关，歌词窗口有时设为「置顶」后仍盖不过主窗口，切换其他软件反而没问题了，暂时无修复方案

**Comment by YanJi314** [comment]
0.0.4 增加了一些代码处理桌面歌词窗口置顶
但本地测试时仍有小概率出现问题 原因未知 疑似是electron的bug
如遇相关问题重新开启桌面歌词即可恢复
