### ISSUE TITLE
任务栏图标菜单永久消失

### ISSUE THREAD

**Issue by nosoftcn** [Simsv-Software/SimMusic2024-Windows#6]
右键任务栏图标后出现菜单，点击打开后，之后菜单永久消失，重启无法恢复（其它软件任可使用）

版本	Windows 11 家庭中文版
版本号	23H2
安装日期	‎2024/‎5/‎28
操作系统版本	22635.4005
体验	Windows Feature Experience Pack 1000.22700.1035.0

**Comment by YanJi314** [comment]
Win11暂未复现

**Comment by YanJi314** [comment]
0.0.4 增加了一些逻辑，应该彻底修复了托盘菜单可能存在的问题
