### ISSUE TITLE
托盘图标无名称

### ISSUE THREAD

**Issue by nosoftcn** [Simsv-Software/SimMusic2024-Windows#8]
移动到托盘图标时，不会出现名称，只有一个无内容框（如图）
![image](https://imgos.cn/2024/08/16/66bebf81e63fa.png)

**Comment by YanJi314** [comment]
下版本将统一添加提示。
> 此图标在先前版本的 Windows 不会显示任何提示，Win11 没活硬整非要显示一个空白 title。

**Comment by YanJi314** [comment]
已修复，将随下版本一并发布
