### ISSUE TITLE
通知中心媒体控制显示Edge浏览器

### ISSUE THREAD

**Issue by nosoftcn** [Simsv-Software/SimMusic2024-Windows#9]
通知中心媒体控制应用显示Edge浏览器并非sim-music，虽然有可能是electron的原因，但还是希望可以改善

**Comment by YanJi314** [comment]
未复现，**且 SimMusic 本身没有任何可能会输出 Edge 的信息**。在多个 App 同时播放时，Windows 会在媒体中心右上角添加切换按钮，可以点击切换到对应的 App，SimMusic 无法控制此行为将自身展示在最前。
![image](https://github.com/user-attachments/assets/f434b8b4-b402-4e38-b920-d74da7da2a3e)

**Comment by nosoftcn** [comment]
有可能win11有两个播放内容，且其中一个没有图标和名称时，使用另一个播放内容的图标和名称

**Comment by YanJi314** [comment]
Win 11，没有安装 Edge，使用 Chrome 无法复现
MediaSession API 并没有提供设置程序名称的选项，且此问题应向微软报告
